#!/bin/bash
cd "$(dirname ${BASH_SOURCE[0]})" || exit 1
git pull
cd lab-01/flux-system || exit 1

# create the namespace
kubectl apply -f namespace.yaml

# create the Flux secret (substitute $PAT)
# the PAT must have permissions to the repo
flux create secret git flux-system -n flux-system --url https://github.com/cse-labs/pizza-labs -u gitops -p $PAT

# deploy the Flux components
kubectl apply -f components.yaml

# create the Flux Source
kubectl apply -f source.yaml

# this single kustomization will manage all of the kustomizations generated by Res-Edge-Automation
kubectl apply -f flux-kustomization.yaml

# check pods for cert-manager and heartbeat
kubectl get pods -A --watch
