---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/lab-01/config/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
