#!/bin/bash

k3d="$CLI_BOA_DIR/k3d.yaml"
# validate directories
if [ ! -f "$k3d" ]; then
	k3d="$CLI_BIN_DIR/.$CLI_BIN_NAME/k3d.yaml"

	if [ ! -f "$k3d" ]; then
		echo "File not found - $k3d"
		exit 1
	fi
fi

kic cluster delete

set -e

echo ""
echo "Creating cluster ..."

k3d cluster create \
    --k3s-arg '--no-deploy=traefik@server:0' \
    --config "$k3d"

echo "waiting for cluster to start"
sleep 10
kubectl wait pods -n kube-system -l k8s-app=kube-dns --for condition=Ready --timeout=30s

echo ""
echo "waiting for cluster metric-server to start"
kubectl wait pods -n kube-system -l k8s-app=metrics-server --for condition=Ready --timeout=30s

echo ""
kubectl get pods -A
