apiVersion: v1
kind: Service
metadata:
  name: pos
  namespace: pos
spec:
  selector:
    app: pos

  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
