apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: config
spec:
  selector:
    app: config

  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
